### ISSUE TITLE
How to display the agenda items instantly?

### ISSUE THREAD

**Issue by hmdnawazz** [cultuurnet/culturefeed_d8#6]
Currently, on /agenda/search page, all the agenda items are displaying.

To update the search results, every time we need to clear the cache. Why it is like that?

So yesterday an agenda item with the date 11 August was displaying.

Today it was also displaying. Then I clear the Drupal cache and then that item has gone.

Is it possible to update the search results without clearing the cache? OR do we need to clear the cache in the code somewhere? Can you please guide me?

**Comment by fienvh** [comment]
@hmdnawazz our developer is unavailable until the end of the month. 
We'll get back to you as soon as he is back. Sorry for the inconvenience

**Comment by zuuperman** [comment]
@hmdnawazz All agenda related content shown on the site, is tagged with a custom cache tag.

There is a drush command available that you can use to invalidate the agenda: https://github.com/cultuurnet/culturefeed_d8/blob/master/modules/culturefeed_search/src/Commands/CultureFeedSearchCommands.php#L43

We are using that command in our cron, to invalidate the agenda every day. You can also choose to invalidate it every hour

**Comment by zuuperman** [comment]
It's not a drupal cron implementation. It's a drush command that is available. We installed a crontab on our server that calls the command:

https://github.com/cultuurnet/culturefeed_d8/blob/master/modules/culturefeed_search/src/Commands/CultureFeedSearchCommands.php#L43

You'll see that it idd clears the same tags like your example. So your code should work.
